import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { LoginApi } from '../features/LoginApi';

const initialState = {
  login: [],
  status: 'idle',
};


export const readAllAsync = createAsyncThunk(
  'login/LoginApi',
  async () => {
    const response = await LoginApi();
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const postSlice = createSlice({
  name: 'login',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {



  }
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.

});